# Generated by Django 4.2.2 on 2023-06-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('efficiency_modifier', models.IntegerField(default=0)),
                ('profitability_modifier', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ore_amount',
        ),
        migrations.AddField(
            model_name='ore',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ore',
            name='profitability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ore',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('ore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.ore')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miner.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pickaxe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miner.pickaxe'),
        ),
    ]
