# Generated by Django 4.2.2 on 2023-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_pickaxe_remove_userprofile_ore_amount_ore_efficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickaxe',
            old_name='efficiency_modifier',
            new_name='efficiency',
        ),
        migrations.RenameField(
            model_name='pickaxe',
            old_name='profitability_modifier',
            new_name='mining_chance_modifier',
        ),
        migrations.RemoveField(
            model_name='ore',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='ore',
            name='profitability',
        ),
        migrations.AddField(
            model_name='ore',
            name='mining_chance',
            field=models.FloatField(default=0),
        ),
    ]
