# Generated by Django 4.2.2 on 2023-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0004_alter_userprofile_pickaxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickaxe',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
    ]
